[workspace]
members = [
    "app",
    "bsp",
    "self-tests",
]

resolver = "2"

[profile.dev]
codegen-units = 1
incremental = false
lto = 'fat'
opt-level = 's'

[profile.test]
codegen-units = 1
incremental = false
lto = 'fat'
opt-level = 's'